name: invasive
batch_size: 32
initial_lr: 0.1
momentum: 0.9
weight_declay: 0.0001
epochs: 90
data_folder: /home/bzhou/Data/invasive
model: densenet161
pretrain: True
print_freq: 10
num_classes: 2
train_val_split: 0.8
regime: None